name: DevOps VLE 5 CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/vidhi-05-jain/devops-lab-app:latest ./app

      - name: Push Docker image
        run: |
          docker push ghcr.io/vidhi-05-jain/devops-lab-app:latest

      - name: Deploy to EC2 Kubernetes
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            kubectl set image deployment/devops-lab-app \
              devops-lab-app=ghcr.io/vidhi-05-jain/devops-lab-app:latest

            kubectl rollout status deployment/devops-lab-app --timeout=180s

            kubectl get pods
